---
- name: update apt packages
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: install Apache Web Server
  apt:
    name: apache2
    state: latest

- name: enable installed Apache Web Server
  service:
    name: apache2
    enabled: yes

- name: Copy custom index.html page to use
  template:
    src: "files/index.html"
    dest: "/var/www/html/index.html"

- name: "install NodeJS & NPM."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy NodeJS server file
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Start NodeJS Web Server
  shell: |
    pm2 start ~/web/index.js -f